server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/crc_db
    username: root
    password:
  security:
    user:
      name: marek
      password: marek
